/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
/* eslint-disable @typescript-eslint/no-explicit-any */
import React from 'react';
import axios from 'axios';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/dist/client/router';
import CharactersItem from '../src/component/CharactersItem/CharactersItem';

import styles from '../styles/Home.module.scss';
import Pagination from '../src/component/Pagination/Pagination';
import CharactersForm from '../src/component/CharactersForm/CharactersForm';

interface CharacterListProps {
  id: number,
  name: string;
  species: string;
  image: string;
  status: string,
}

const defaultData = 'https://rickandmortyapi.com/api/character/';

export const getServerSideProps: GetServerSideProps = async () => {
  const charactersList = await axios.get(defaultData).then(({ data }) => data.results);
  const totalPage = await axios.get('https://rickandmortyapi.com/api/character/').then(({ data }) => data.info.pages);

  return {
    props: {
      charactersList,
      totalPage,
    },
  };
};

const Home = ({ charactersList, totalPage }: any): JSX.Element => (
  <div className={styles.container}>
    <Head>
      <title>Rick And Morty</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <CharactersForm />

      <div className={styles.charachers}>
        {charactersList.map((person: CharacterListProps) => (
          <CharactersItem
            key={person.id}
            name={person.name}
            species={person.species}
            image={person.image}
            stat={person.status}
            id={person.id}
          />
        ))}
      </div>
      <Pagination totalPage={totalPage} />
    </main>

  </div>
);
export default Home;
