import React from 'react';
import Head from 'next/head';
import Link from 'next/link';

import styles from '../styles/Home.module.scss';

const Home = (): JSX.Element => (
  <div className={styles.container}>
    <Head>
      <title>Rick And Morty</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <div>
        <h1>Rick And Morty Api</h1>
        <Link href="/page/1">
          <h4 className={styles.button}>Find your Characters</h4>
        </Link>
      </div>
    </main>

  </div>
);

export default Home;
